name: jtm
favicon: null
layout_spectrum: 0.6727338281925768
typography_spectrum: 0.8958225059323013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.378303969046101
  lightness: 0.8507358622737229
  saturation: 0.3717208511661738
  rhythmicContrast: 0.6650758646428585
purpose: []
